# SPDX-License-Identifier: GPL-2.0

rpmi-tee-bus-y = bus.o
rpmi-tee-core-objs := $(rpmi-tee-bus-y)
obj-$(CONFIG_RISCV_RPMI_TEE_TRANSPORT) = rpmi-tee-core.o
rpmi-tee-driver-y = driver.o sysinfo.o
rpmi-tee-module-objs := $(rpmi-tee-driver-y)
obj-$(CONFIG_RISCV_RPMI_TEE_TRANSPORT) += rpmi-tee-module.o
